version: "3.7"
services:
  csweb:
    build: 
      context: './'
      args:
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        DEFAULT_TIMEZONE: "${TIMEZONE}" 
        API_URL: "${API_URL}"
        PROXY_PATH: "${PROXY_PATH}"
        TZ: "${TIMEZONE}"
    volumes:
      - ./.vols/csweb-files:/var/www/html/${PROXY_PATH}/files
    networks:
      - frontend
      - backend
    ports: 
      - "${CSWEB_PORT}:80"
    depends_on: 
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.vols/db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TIMEZONE}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: '${URL}/${PHPMYADMIN_PATH}/'
      TZ: "${TIMEZONE}"
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
networks:
  frontend:
  backend:
volumes:
    db_data:
    csweb_files:
